name: Test Secrets

on:
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Show secret names
        run: |
          echo "VPS_HOST is set: ${{ secrets.VPS_HOST != '' }}"
          echo "VPS_USER is set: ${{ secrets.VPS_USER != '' }}"
          echo "VPS_KEY is set: ${{ secrets.VPS_KEY != '' }}"
